#!/usr/bin/env python3
"""Compile event_websites.json from agent results."""
import sys, io, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

data = {}

def add(name, website, partners=None):
    data[name] = {"website": website, "partners_page": partners}

# === BATCH 1 ===
add("10K Montmartre", "https://www.10kmontmartreag2rlamondiale.fr/en")
add("10K Valencia Ibercaja by Kiprun", "https://10kvalencia.com/", "https://10kvalencia.com/category/sponsors/")
add("Harmonie Mutuelle 20k de Tours", "https://harmonie-mutuelle.marathon1020ktours.com/", "https://harmonie-mutuelle.marathon1020ktours.com/partenaires")
add("21K de Montréal", "https://couronsmtl.com/en/21k/home/", "https://couronsmtl.com/en/marathon-beneva/partners/")
add("AJ Bell Great Birmingham Run", "https://www.greatrun.org/events/great-birmingham-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great Birmingham Run 10K", "https://www.greatrun.org/events/great-birmingham-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great Bristol Run", "https://www.greatrun.org/events/great-bristol-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great Bristol Run 10K", "https://www.greatrun.org/events/great-bristol-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great Manchester Run", "https://www.greatrun.org/events/great-manchester-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great North 10K", "https://www.greatrun.org/events/great-north-10k/", "https://www.greatrun.org/partners/")
add("AJ Bell Great North Run", "https://www.greatrun.org/events/great-north-run/", "https://www.greatrun.org/partners/")
add("AJ Bell Great South Run", "https://www.greatrun.org/events/great-south-run/", "https://www.greatrun.org/partners/")
add("ASICS LDNX", "https://ldnx.co.uk/")
add("ASICS Los Angeles Marathon", "https://www.lamarathon.com/", "https://www.mccourtfoundation.org/event/los-angeles-marathon/partners-media/")
add("Abalone Marathon de Nantes", "https://www.marathondenantes.com/", "https://www.marathondenantes.com/partenaires")
add("Acea Run Rome The Marathon", "https://www.runromethemarathon.com/")
add("Adidas 10K Paris", "https://www.adidas10kparis.fr/en", "https://www.adidas10kparis.fr/en/the-race/partners")
add("Adidas Manchester Marathon", "https://www.manchestermarathon.co.uk/", "https://www.manchestermarathon.co.uk/official-event-partners/")
add("Aramco Houston Half Marathon", "https://www.chevronhoustonmarathon.com/", "https://www.chevronhoustonmarathon.com/sponsors/")
add("Army Ten Miler", "https://www.armytenmiler.com/", "https://www.armytenmiler.com/about-atm/sponsors/")
add("Asics Run Melbourne", "https://runmelbourne.com.au/")
add("Athens Marathon", "https://www.athensauthenticmarathon.gr/en", "https://www.athensauthenticmarathon.gr/en/sponsors")
add("Atlanta Journal-Constitution Peachtree Road Race", "https://www.atlantatrackclub.org/", "https://www.atlantatrackclub.org/sponsors")
add("Austin Marathon", "https://youraustinmarathon.com/", "https://youraustinmarathon.com/sponsors/")
add("BMW Berlin Marathon", "https://www.bmw-berlin-marathon.com/en/", "https://www.bmw-berlin-marathon.com/en/sponsoren-partner/sponsors-partners")
add("BMW Dallas Marathon", "https://dallasmarathon.com/", "https://dallasmarathon.com/dallas-marathon-festival/partners")
add("BOLDERBoulder 10K", "https://www.bolderboulder.com/", "https://www.bolderboulder.com/bolder-sponsors/")
add("Baltimore Running Festival", "https://www.thebaltimoremarathon.com/")
add("Bangsaen10", "https://www.bangsaen42.com/en")
add("Bangsaen21", "https://www.bangsaen42.com/en")
add("Bangsaen42 Chonburi Marathon", "https://www.bangsaen42.com/en")
add("Bank of America Chicago Marathon", "https://www.chicagomarathon.com/", "https://www.chicagomarathon.com/sponsors/sponsors/")
add("Bank of America Shamrock Shuffle", "https://www.chicagomarathon.com/")
add("Bay to Breakers", "https://www.baytobreakers.com/")
add("Beijing Marathon", "https://www.beijing-marathon.com/")
add("Boilermaker Road Race", "https://www.boilermaker.com/", "https://www.boilermaker.com/community/corporate-partnership/")
add("Boston Marathon", "https://www.baa.org/races/boston-marathon/", "https://www.baa.org/partners/sponsors/")
add("Brighton Marathon", "https://www.londonmarathonevents.co.uk/brighton-marathon-weekend")
add("Broad Street Run", "https://www.broadstreetrun.com/", "https://www.broadstreetrun.com/partners/")
add("Broløbet - The Bridge Run", "https://bridgerun2025.com/", "https://bridgerun2025.com/sponsorer-partnere/")
add("Burj2Burj Half Marathon", "https://www.burj2burj.com/", "https://www.burj2burj.com/partners")
add("California International Marathon", "https://runsra.org/california-international-marathon/", "https://runsra.org/california-international-marathon/sponsors/")
add("Cancer Research UK London Winter Run", "https://www.londonwinterrun.co.uk/")
add("Cardiff Half Marathon", "https://www.cardiffhalfmarathon.co.uk/", "https://www.cardiffhalfmarathon.co.uk/our-community/sponsors/")
add("Chevron Houston Marathon", "https://www.chevronhoustonmarathon.com/", "https://www.chevronhoustonmarathon.com/sponsors/")
add("City2Surf", "https://city2surf.com.au/", "https://city2surf.com.au/partners/")

# === BATCH 2 ===
add("Coelmo Napoli City Half Marathon", "https://www.napolirunning.com/nchm/?lang=en", "https://www.napolirunning.com/partners/")
add("Columbus Marathon", "https://www.columbusmarathon.com/")
add("Cooper River Bridge Run", "https://bridgerun.com/", "https://bridgerun.com/sponsors-vendors/")
add("Copenhagen Half Marathon", "https://cphhalf.dk/en/", "https://cphhalf.dk/en/sponsors-partners/")
add("Copenhagen Marathon", "https://copenhagenmarathon.dk/en/", "https://copenhagenmarathon.dk/en/sponsors-partners/")
add("Cowtown Marathon", "https://cowtownmarathon.org/")
add("Credit Union Cherry Blossom", "https://www.cherryblossom.org/", "https://www.cherryblossom.org/about/partners/sponsors/")
add("Crescent City Classic", "https://ccc10k.com/", "https://ccc10k.com/sponsors/")
add("Dam tot Damloop", "https://www.nndamloop.nl/", "https://www.nndamloop.nl/sponsors")
add("Denver Colfax Marathon", "https://www.runcolfax.org/", "https://www.runcolfax.org/companies/our-sponsors-2/")
add("Detroit Marathon", "https://www.freepmarathon.com/", "https://www.freepmarathon.com/sponsors/")
add("Dick's Pittsburgh Marathon", "https://www.thepittsburghmarathon.com/", "https://www.thepittsburghmarathon.com/sponsors")
add("Disney Princess Half Marathon", "https://www.rundisney.com/events/disneyworld/disney-princess-half-marathon-weekend")
add("EDP Lisboa Meia Maratona", "https://maratonaclubedeportugal.com/en/", "https://maratonaclubedeportugal.com/en/partners-edp-meia-maratona-de-lisboa/")
add("EDP Maratona de Lisboa", "https://maratonaclubedeportugal.com/en/", "https://maratonaclubedeportugal.com/en/partners-edp-maratona-de-lisboa/")
add("EDP Meia Maratona de Lisboa - Vodafone 10K", "https://maratonaclubedeportugal.com/en/", "https://maratonaclubedeportugal.com/en/partners-edp-meia-maratona-de-lisboa/")
add("Eugene Marathon", "https://www.eugenemarathon.com/", "https://www.eugenemarathon.com/sponsors")
add("Eurospin RomaOstia Half Marathon", "https://www.romehalfmarathon.it/en/")
add("Falmouth Road Race", "https://falmouthroadrace.com/", "https://falmouthroadrace.com/sponsors/our-sponsors/")
add("Fargo Marathon", "https://fargomarathon.com/", "https://fargomarathon.com/sponsorship/")
add("Flying Pig Marathon", "https://flyingpigmarathon.com/", "https://flyingpigmarathon.com/get-involved/sponsorship")
add("Gasparilla Distance Classic", "https://www.rungasparilla.com/", "https://www.rungasparilla.com/sponsors/")
add("Gate River Run", "https://gateriverrun15k.com/")
add("Generali Berlin Half Marathon", "https://www.generali-berliner-halbmarathon.de/en/", "https://www.generali-berliner-halbmarathon.de/en/sponsoren-partner/sponsors-partners")
add("Generali Prague Half Marathon", "https://www.runczech.com/en/events/generali-prague-half-marathon-2026")
add("GetPro Bath Half", "https://www.londonmarathonevents.co.uk/bath-half")
add("Gold Coast Marathon", "https://goldcoastmarathon.com.au/", "https://goldcoastmarathon.com.au/about-2/sponsors/")
add("Grandma's Marathon", "https://grandmasmarathon.com/", "https://grandmasmarathon.com/support/sponsors/")
add("Great Scottish Run", "https://www.greatrun.org/events/great-scottish-run/", "https://www.greatrun.org/partners/")
add("Great Scottish Run 10K", "https://www.greatrun.org/events/great-scottish-run/", "https://www.greatrun.org/partners/")
add("Göteborgsvarvet", "https://www.goteborgsvarvet.se/en", "https://www.goteborgsvarvet.se/partners")
add("HOKA Semi de Paris", "https://www.hokasemideparis.fr/en", "https://www.hokasemideparis.fr/en/races/partners")
add("Half Marathon Munchen by Brooks", "https://marathonmuenchen.org/en/", "https://marathonmuenchen.org/en/sponsors-partners/")
add("Harmonie Mutuelle 20km de Paris", "https://harmonie-mutuelle.20kmparis.com/en/", "https://harmonie-mutuelle.20kmparis.com/en/partenaires/")
add("Harmonie Mutuelle 10km de Tours", "https://harmonie-mutuelle.marathon1020ktours.com/", "https://harmonie-mutuelle.marathon1020ktours.com/partenaires")
add("Harmonie Mutuelle Toulouse Metropole Run Experience", "https://harmonie-mutuelle.toulouserunexperience.fr/", "https://harmonie-mutuelle.toulouserunexperience.fr/nos-partenaires/")
add("Haspa Marathon Hamburg", "https://haspa-marathon-hamburg.de/en/", "https://www.haspa-marathon-hamburg.de/en/sponsors-and-partners")
add("Hoag OC Marathon", "https://ocmarathon.com/", "https://ocmarathon.com/partnerships/")
add("Hoka Runaway Sydney Half Marathon", "https://runawaysydneyhalf.com.au/", "https://runawaysydneyhalf.com.au/partners/")
add("Honolulu Marathon", "https://www.honolulumarathon.org/")
add("Hyundai Meia Maratona", "https://www.meiamaratonadoporto.com/")
add("IU Health 500 Festival Mini-Marathon", "https://indymini.com/")
add("Indianapolis Monumental Marathon", "https://monumentalmarathon.com/", "https://monumentalmarathon.com/sponsorship/")
add("Irish Life Dublin Marathon", "https://irishlifedublinmarathon.ie/", "https://irishlifedublinmarathon.ie/sponsors/")
add("Istanbul Marathon", "https://maraton.istanbul/?lang=en", "https://maraton.istanbul/sponsorluk/")
add("Kagawa Marugame International Half Marathon", "https://www.km-half.com/english/")
add("Life Time Chicago Half Marathon & 5K", "https://www.chicagohalfmarathon.com/", "https://www.chicagohalfmarathon.com/sponsors/")
add("Lilac Bloomsday Run", "https://bloomsdayrun.org/", "https://bloomsdayrun.org/sponsors/")
add("London Landmarks Half Marathon", "https://llhm.co.uk/", "https://llhm.co.uk/partners-sponsorships")
add("Long Beach Marathon", "https://www.runlongbeach.com/", "https://runlongbeach.com/partners-exhibitors/")
add("Mainova Frankfurt Marathon", "https://www.frankfurt-marathon.com/en/", "https://www.frankfurt-marathon.com/en/sponsors/")
add("Manchester Half Marathon", "https://www.manchesterhalfmarathon.com/")

# === BATCH 3 ===
add("Manchester Road Race", "https://manchesterroadrace.com/")
add("Harmonie Mutuelle Marathon de Tours", "https://runningloirevalley.com/", "https://harmonie-mutuelle.marathon1020ktours.com/partenaires")
add("Maratón de la Ciudad de México Telcel", "https://maraton.cdmx.gob.mx/", "https://maraton.cdmx.gob.mx/socios")
add("Marine Corps Marathon", "https://www.marinemarathon.com/", "https://www.marinemarathon.com/sponsors/")
add("Marseille-Cassis AG2R La Mondiale", "https://www.marseille-cassis.com/en/", "https://www.marseille-cassis.com/en/partenaires/nos-partenaires")
add("Media Maraton de Bogota", "https://www.mediamaratonbogota.com/", "https://www.mediamaratonbogota.com/en/sponsors")
add("Medio Maraton de Sevilla", "https://www.mediomaratondesevilla.es/", "https://en.mediomaratondesevilla.es/ems-patrocinio")
add("Medtronic Twin Cities Marathon", "https://www.tcmevents.org/", "https://www.tcmevents.org/eventsponsorship")
add("Miami Marathon", "https://www.themiamimarathon.com/", "https://www.themiamimarathon.com/sponsors/")
add("Milano Marathon", "https://www.milanomarathon.it/en/", "https://www.milanomarathon.it/en/sponsors/")
add("Mitja Marato Barcelona by Brooks", "https://www.mitjamarato.barcelona/en/", "https://www.mitjamarato.barcelona/en/sponsors/")
add("Movistar Madrid Medio Maraton", "https://en.mediomaratonmadrid.es/")
add("NYCRUNS Brooklyn Experience Half Marathon", "https://nycruns.com/")
add("NYRR RBC Brooklyn Half", "https://www.nyrr.org/")
add("NN CPC Loop Den Haag - Half Marathon", "https://nncpcloopdenhaag.nl/en/", "https://www.nncpcloopdenhaag.nl/info/sponsors-partners/")
add("NN CPC Loop Den Haag - 10 KM Loop", "https://nncpcloopdenhaag.nl/en/", "https://www.nncpcloopdenhaag.nl/info/sponsors-partners/")
add("NN Marathon Rotterdam", "https://nnmarathonrotterdam.nl/en/", "https://nnmarathonrotterdam.nl/en/sponsors/")
add("NN Maraton Warszawski", "https://nnmaratonwarszawski.com/en/", "https://nnmaratonwarszawski.com/en/partners/")
add("NN San Silvestre Vallecana", "https://sansilvestrevallecana.com/")
add("Nike Melbourne Marathon Festival", "https://melbournemarathon.com.au/", "https://melbournemarathon.com.au/partners/")
add("Oklahoma City Memorial Marathon", "https://okcmarathon.com/", "https://okcmarathon.com/get-involved/sponsors/")
add("Osaka Marathon", "https://www.osaka-marathon.com/2026/en/")
add("Portland Marathon", "https://www.portlandmarathon.com/", "https://www.portlandmarathon.com/sponsors")
add("Prague International Marathon", "https://www.runczech.com/en/")
add("Richmond Marathon", "https://www.richmondmarathon.org/", "https://www.richmondmarathon.org/race-weekend/sponsors/")
add("Riyadh Marathon", "https://www.riyadhmarathon.org/en/")
add("Rock 'n' Roll Arizona Marathon", "https://www.runrocknroll.com/events/arizona", "https://www.runrocknroll.com/info/partners")
add("Rock 'n' Roll Running Series Las Vegas", "https://www.runrocknroll.com/events/las-vegas", "https://www.runrocknroll.com/info/partners")
add("Rock 'n' Roll Running Series Mexico City", "https://www.runrocknroll.com/events/mexico-city", "https://www.runrocknroll.com/info/partners")
add("Rock 'n' Roll Running Series San Diego", "https://www.runrocknroll.com/events/san-diego", "https://www.runrocknroll.com/info/partners")
add("St. Jude Rock 'n' Roll Series Nashville", "https://www.runrocknroll.com/events/nashville", "https://www.runrocknroll.com/info/partners")
add("St. Jude Rock 'n' Roll Running Series Washington DC", "https://www.runrocknroll.com/events/washington-dc", "https://www.runrocknroll.com/info/partners")
add("Royal Parks Half Marathon", "https://www.royalparkshalf.com/", "https://www.royalparkshalf.com/partners")
add("Royal Run", "https://royalrun.dk/", "https://royalrun.dk/om-royal-run/samarbejdspartnere/")
add("Run in Lyon", "https://www.runinlyon.com/en/", "https://www.runinlyon.com/en/races/partners")
add("San Antonio Marathon", "https://sanantoniomarathon.com/", "https://sanantoniomarathon.com/sponsors/")
add("San Francisco Marathon", "https://www.thesfmarathon.com/", "https://www.thesfmarathon.com/partners/")
add("Sanlam Cape Town Marathon", "https://capetownmarathon.com/")
add("Schneider Electric Marathon de Paris", "https://www.schneiderelectricparismarathon.com/", "https://www.schneiderelectricparismarathon.com/fr/l-evenement/partenaires")
add("Seoul Marathon", "http://en.seoul-marathon.com/")
add("Shamrock Marathon", "https://www.shamrockmarathon.com/", "https://www.shamrockmarathon.com/sponsors/become-a-sponsor/")
add("Shamrock Run Portland", "https://www.shamrockrun.com/")
add("Shanghai Marathon", "https://static.shang-ma.com/web/index.html")
add("Silicon Valley Turkey Trot", "https://www.svturkeytrot.com/", "https://www.svturkeytrot.com/sponsors/")
add("St. Jude Memphis Marathon", "https://www.stjude.org/get-involved/fitness-fundraisers/memphis-marathon.html", "https://www.stjude.org/get-involved/fitness-fundraisers/memphis-marathon/event-information/sponsors.html")
add("Standard Chartered Dubai Marathon", "https://www.dubaimarathon.org/", "https://www.dubaimarathon.org/event-sponsor/support-sponsors/")
add("Standard Chartered Hong Kong Marathon", "https://www.hkmarathon.com/", "https://www.hkmarathon.com/sponsors-corner")

# === BATCH 4 ===
add("Standard Chartered Hong Kong Half Marathon", "https://www.hkmarathon.com/", "https://www.hkmarathon.com/sponsors-corner")
add("Standard Chartered KL Marathon", "https://www.kl-marathon.com/", "https://www.kl-marathon.com/sponsorspromotions/sponsors/")
add("Standard Chartered KL Half Marathon", "https://www.kl-marathon.com/", "https://www.kl-marathon.com/sponsorspromotions/sponsors/")
add("Standard Chartered KL 10K", "https://www.kl-marathon.com/", "https://www.kl-marathon.com/sponsorspromotions/sponsors/")
add("Standard Chartered Singapore Marathon", "https://www.singaporemarathon.com/", "https://www.singaporemarathon.com/community/sponsors/")
add("Standard Chartered Singapore Half Marathon", "https://www.singaporemarathon.com/", "https://www.singaporemarathon.com/community/sponsors/")
add("Statesman Capitol 10K", "https://www.cap10k.com/", "https://www.cap10k.com/sponsorships/")
add("Stockholm Marathon", "https://www.stockholmmarathon.se/eng/", "https://www.stockholmmarathon.se/start/samarbetspartners/")
add("TCS Amsterdam Marathon", "https://www.tcsamsterdammarathon.eu/", "https://www.tcsamsterdammarathon.eu/sponsors")
add("TCS London Marathon", "https://www.londonmarathonevents.co.uk/london-marathon", "https://www.londonmarathonevents.co.uk/london-marathon/our-sponsors")
add("TCS Mizuno Half Marathon", "https://www.tcsamsterdammarathon.eu/mizuno-half-marathon", "https://www.tcsamsterdammarathon.eu/sponsors")
add("TCS New York City Marathon", "https://www.nyrr.org/tcsnycmarathon", "https://www.nyrr.org/tcsnycmarathon/PARTNERS")
add("TCS Sydney Marathon presented by ASICS", "https://www.tcssydneymarathon.com/", "https://www.tcssydneymarathon.com/eventpartners")
add("TCS Toronto Waterfront Marathon", "https://www.torontowaterfrontmarathon.com/", "https://www.torontowaterfrontmarathon.com/partnerships/")
add("Taipei Half Marathon", "https://scbmarathon.com/")
add("Taipei Marathon", "https://www.taipeicitymarathon.com/en/")
add("Tata Mumbai Marathon", "https://tatamumbaimarathon.procam.in/", "https://tatamumbaimarathon.procam.in/about-us/title-sponsor")
add("The Big Half", "https://www.londonmarathonevents.co.uk/big-half", "https://www.londonmarathonevents.co.uk/big-half/our-sponsors")
add("Tokyo Legacy Half Marathon", "https://legacyhalf.tokyo/en/", "https://legacyhalf.tokyo/en/about/official-partner/index.html")
add("Tokyo Marathon", "https://www.marathon.tokyo/en/", "https://www.marathon.tokyo/en/about/official-partner/")
add("Transurban Bridge to Brisbane", "https://bridgetobrisbane.com.au/", "https://bridgetobrisbane.com.au/partners/")
add("Ukrop's Monument Avenue 10K", "https://www.sportsbackers.org/event/ukrops-monument-avenue-10k/")
add("United Airlines NYC Half", "https://www.nyrr.org/", "https://www.nyrr.org/about/partners")
add("Valencia Half Marathon Trinidad Alfonso Zurich", "https://www.valenciaciudaddelrunning.com/en/half/half-marathon/", "https://www.valenciaciudaddelrunning.com/en/half/sponsors-half-marathon/")
add("Valencia Marathon Trinidad Alfonso Zurich", "https://www.valenciaciudaddelrunning.com/en/marathon/maraton/", "https://www.valenciaciudaddelrunning.com/en/marathon/sponsors-marathon/")
add("Vancouver Sun Run", "https://www.vancouversunrun.com/", "https://www.vancouversunrun.com/sponsors/")
add("Vedanta Delhi Half Marathon", "https://vedantadelhihalfmarathon.procam.in/")
add("Vienna City Half Marathon", "https://www.vienna-marathon.com/", "https://www.vienna-marathon.com/?go=sponsoring")
add("Vienna City Marathon", "https://www.vienna-marathon.com/", "https://www.vienna-marathon.com/?go=sponsoring")
add("Vitality London 10,000", "https://www.vitalitylondon10000.co.uk/")
add("Walt Disney World Marathon Weekend", "https://www.rundisney.com/events/disneyworld/disneyworld-marathon-weekend")
add("Warsaw Half Marathon", "https://polmaratonwarszawski.com/en/", "https://polmaratonwarszawski.com/sponsorzy_i_partnerzy/")
add("Wizz Air Rome Half Marathon by Brooks", "https://www.romehalfmarathon.it/en/")
add("Zurich Marató de Barcelona", "https://www.zurichmaratobarcelona.es/en/", "https://www.zurichmaratobarcelona.es/en/sponsors/")
add("Zurich Maratón de Sevilla", "https://en.zurichmaratonsevilla.es/")
add("Zurich Rock 'n' Roll Running Series Madrid", "https://rocknrollmadridrun.com/?lang=en", "https://rocknrollmadridrun.com/sponsors/?lang=en")
add("Saucony London 10K", "https://www.thelondon10k.com/")

total = len(data)
with_partners = sum(1 for v in data.values() if v['partners_page'])
print(f"Total: {total} events")
print(f"With partners page: {with_partners} ({100*with_partners/total:.0f}%)")
print(f"Without: {total - with_partners}")

with open('event_websites.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print("Saved to event_websites.json")
